apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: baremetal-operator-system
resources:
- https://github.com/metal3-io/baremetal-operator/releases/latest/download/baremetal-operator.yaml

configMapGenerator:
- name: ironic
  namespace: baremetal-operator-system
  behavior: replace
  literals:
  - IRONIC_NAME=ironic
