apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: baremetal-operator-system
resources:
- https://github.com/metal3-io/baremetal-operator/ironic-deployment/overlays/basic-auth_tls?ref=main

configMapGenerator:
- envs:
  - ironic_bmo_configmap.env
  name: ironic-bmo-configmap
  behavior: create

patches:
# The TLS component adds certificates but it cannot know the exact IPs of our environment.
# Here we patch the certificates to have the correct IPs.
- patch: |-
    - op: replace
      path: /spec/ipAddresses/0
      value: 192.168.0.127
  target:
    kind: Certificate
    name: ironic-cert

# Generate the necessary secrets:
secretGenerator:
- behavior: create
  envs:
  - ironic-htpasswd
  name: ironic-htpasswd

images:
- name: quay.io/metal3-io/ironic
  newTag: "v29.0.0"
