apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: InfrastructureProvider
metadata:
  name: openstack
  namespace: capo-system
spec:
  version: v0.14.0
  manager:
    featureGates:
      PriorityQueue: true
      AutoScaleFromZero: true
---
apiVersion: v1
kind: Namespace
metadata:
  name: capo-system
