apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: InfrastructureProvider
metadata:
  name: metal3
  namespace: capm3-system
spec:
  version: v1.12.1
---
apiVersion: v1
kind: Namespace
metadata:
  name: capm3-system
