apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ironic-standalone-operator-system

resources:
- https://github.com/metal3-io/ironic-standalone-operator/releases/latest/download/install.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: ironic-standalone-operator-ironic-standalone-operator-config
  namespace: ironic-standalone-operator-system
  behavior: replace
  literals:
  # - IPA_BASEURI=http://192.168.222.1
  - IPA_BASEURI=https://artifactory.nordix.org/artifactory/openstack-remote-cache/ironic-python-agent/dib
