apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: baremetal-operator-system
resources:
- ../ironic

patches:
- path: ironic-patch.yaml
- patch: |-
    - op: replace
      path: /spec/ipAddresses/0
      value: 192.168.222.3
  target:
    kind: Certificate
    name: ironic-cert
