apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: baremetal-operator-system
resources:
- ironic.yaml
- certificate.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- behavior: create
  files:
  - htpasswd
  - password
  - username
  name: ironic-credentials
