apiVersion: cluster.x-k8s.io/v1beta2
kind: MachineDeployment
metadata:
  name: kamaji-metal3
  labels:
    cluster.x-k8s.io/cluster-name: kamaji-metal3
spec:
  clusterName: kamaji-metal3
  replicas: 1
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: kamaji-metal3
  rollout:
    strategy:
      rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1
      type: RollingUpdate
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: kamaji-metal3
    spec:
      clusterName: kamaji-metal3
      version: v1.33.0
      bootstrap:
        configRef:
          name: kamaji-metal3-workers
          apiGroup: bootstrap.cluster.x-k8s.io
          kind: KubeadmConfigTemplate
      infrastructureRef:
        name: kamaji-metal3-workers
        apiGroup: infrastructure.cluster.x-k8s.io
        kind: Metal3MachineTemplate
