apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: capi
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: playground
  path: "./gitops/kustomizations/capi"
  prune: true
