apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- cluster.yaml
- metal3cluster.yaml
- kcp.yaml
- kct.yaml
- machinedeployment.yaml
- metal3machinetemplate-v1.34.0.yaml
- metal3machinetemplate-v1.34.1.yaml
- metal3datatemplate.yaml
- ippool.yaml
