apiVersion: cluster.x-k8s.io/v1beta2
kind: MachineDeployment
metadata:
  name: metal3-k8s-workers
  labels:
    cluster.x-k8s.io/cluster-name: metal3-k8s
spec:
  clusterName: metal3-k8s
  replicas: 0
  selector:
    matchLabels:
      machinedeployment: metal3-k8s-workers
  rollout:
    strategy:
      rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1
      type: RollingUpdate
  template:
    metadata:
      labels:
        machinedeployment: metal3-k8s-workers
        cluster.x-k8s.io/cluster-name: metal3-k8s
    spec:
      clusterName: metal3-k8s
      version: v1.34.0
      bootstrap:
        configRef:
          apiGroup: bootstrap.cluster.x-k8s.io
          kind: KubeadmConfigTemplate
          name: metal3-k8s-workers
      infrastructureRef:
        apiGroup: infrastructure.cluster.x-k8s.io
        kind: Metal3MachineTemplate
        name: metal3-k8s-workers-v1.34.0
