apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: baremetal-operator-system
resources:
- https://github.com/metal3-io/baremetal-operator/config/overlays/basic-auth_tls?ref=main

images:
- name: quay.io/metal3-io/baremetal-operator
  newTag: v0.11.2

configMapGenerator:
- name: ironic
  behavior: create
  envs:
  - ironic.env
