apiVersion: cluster.x-k8s.io/v1beta2
kind: MachineDeployment
metadata:
  name: md-kamaji-1
  namespace: default
  labels:
    cluster.x-k8s.io/cluster-name: kamaji-1
    nodepool: nodepool-0
spec:
  clusterName: kamaji-1
  replicas: 1
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: kamaji-1
      nodepool: nodepool-0
  rollout:
    strategy:
      rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1
      type: RollingUpdate
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: kamaji-1
        nodepool: nodepool-0
    spec:
      clusterName: kamaji-1
      version: v1.33.0
      bootstrap:
        configRef:
          name: kamaji-1-workers
          apiGroup: bootstrap.cluster.x-k8s.io
          kind: KubeadmConfigTemplate
      infrastructureRef:
        name: kamaji-1-workers
        apiGroup: infrastructure.cluster.x-k8s.io
        kind: Metal3MachineTemplate
