apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- openstackcluster.yaml
- openstackmachinetemplates.yaml
patches:
- target:
    kind: KubeadmControlPlane
    name: lennart-test-control-plane
  path: kcp-patch.yaml
