apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- flux.yaml
- gitrepository.yaml
- notifications.yaml
- kustomizations/cert-manager.yaml
- kustomizations/capi-operator.yaml
- kustomizations/capi.yaml
- kustomizations/orc.yaml
